### ISSUE TITLE
Arduino problems

### ISSUE THREAD

**Issue by Arda-Coskun** [robotzero1/esp32cam-access-control#1]
When I try to upload the code to esp32-Cam I met with lots of problems in Arduino.

**Comment by robotzero1** [comment]
Did you follow the tutorial? What messages did you see in Arduino?

**Comment by Arda-Coskun** [comment]
yes I follow the tutorial

**Comment by robotzero1** [comment]
You have to describe the problems.

**Comment by Arda-Coskun** [comment]
Arduino:1.8.12 (Windows Store 1.8.33.0) (Windows 10), Kart:"ESP32 Wrover Module, Face Recognition (2621440 bytes), QIO, 80MHz, 921600, Verbose"

FaceDoorEntryESP32Cam:200:26: error: 'face_id_name_list' was not declared in this scope

 static inline int do_enrollment(face_id_name_list *face_list, dl_matrix3d_t *new_id)

                          ^

FaceDoorEntryESP32Cam:200:45: error: 'face_list' was not declared in this scope

 static inline int do_enrollment(face_id_name_list *face_list, dl_matrix3d_t *new_id)

                                             ^

FaceDoorEntryESP32Cam:200:70: error: expected primary-expression before '*' token

 static inline int do_enrollment(face_id_name_list *face_list, dl_matrix3d_t *new_id)

                                                                      ^

FaceDoorEntryESP32Cam:200:71: error: 'new_id' was not declared in this scope

 static inline int do_enrollment(face_id_name_list *face_list, dl_matrix3d_t *new_id)

                                                                       ^

FaceDoorEntryESP32Cam:200:77: error: expression list treated as compound expression in initializer [-fpermissive]

 static inline int do_enrollment(face_id_name_list *face_list, dl_matrix3d_t *new_id)

                                                                             ^

D:\FaceDoorEntryESP32Cam\FaceDoorEntryESP32Cam.ino: In function 'mtmn_config_t app_mtmn_config()':

FaceDoorEntryESP32Cam:52:15: error: 'struct mtmn_config_t' has no member named 'type'

   mtmn_config.type = FAST;

               ^

FaceDoorEntryESP32Cam:52:22: error: 'FAST' was not declared in this scope

   mtmn_config.type = FAST;

                      ^

FaceDoorEntryESP32Cam:55:15: error: 'struct mtmn_config_t' has no member named 'pyramid_times'

   mtmn_config.pyramid_times = 4;

               ^

D:\FaceDoorEntryESP32Cam\FaceDoorEntryESP32Cam.ino: At global scope:

FaceDoorEntryESP32Cam:69:1: error: 'face_id_name_list' does not name a type

 face_id_name_list st_face_list;

 ^

FaceDoorEntryESP32Cam:88:20: error: 'ENROLL_NAME_LEN' was not declared in this scope

   char enroll_name[ENROLL_NAME_LEN];

                    ^

D:\FaceDoorEntryESP32Cam\FaceDoorEntryESP32Cam.ino: In function 'void app_facenet_main()':

FaceDoorEntryESP32Cam:195:22: error: 'st_face_list' was not declared in this scope

   face_id_name_init(&st_face_list, FACE_ID_SAVE_NUMBER, ENROLL_CONFIRM_TIMES);

                      ^

FaceDoorEntryESP32Cam:195:77: error: 'face_id_name_init' was not declared in this scope

   face_id_name_init(&st_face_list, FACE_ID_SAVE_NUMBER, ENROLL_CONFIRM_TIMES);

                                                                             ^

FaceDoorEntryESP32Cam:197:50: error: 'read_face_id_from_flash_with_name' was not declared in this scope

   read_face_id_from_flash_with_name(&st_face_list);

                                                  ^

D:\FaceDoorEntryESP32Cam\FaceDoorEntryESP32Cam.ino: At global scope:

FaceDoorEntryESP32Cam:200:33: error: 'do_enrollment' declared as an 'inline' variable

 static inline int do_enrollment(face_id_name_list *face_list, dl_matrix3d_t *new_id)

                                 ^

FaceDoorEntryESP32Cam:200:33: error: redefinition of 'int do_enrollment'

D:\FaceDoorEntryESP32Cam\FaceDoorEntryESP32Cam.ino:200:12: note: 'int do_enrollment' previously defined here

 static inline int do_enrollment(face_id_name_list *face_list, dl_matrix3d_t *new_id)

            ^

FaceDoorEntryESP32Cam:200:33: error: 'face_id_name_list' was not declared in this scope

 static inline int do_enrollment(face_id_name_list *face_list, dl_matrix3d_t *new_id)

                                 ^

FaceDoorEntryESP32Cam:200:52: error: 'face_list' was not declared in this scope

 static inline int do_enrollment(face_id_name_list *face_list, dl_matrix3d_t *new_id)

                                                    ^

FaceDoorEntryESP32Cam:200:77: error: expected primary-expression before '*' token

 static inline int do_enrollment(face_id_name_list *face_list, dl_matrix3d_t *new_id)

                                                                             ^

FaceDoorEntryESP32Cam:200:78: error: 'new_id' was not declared in this scope

 static inline int do_enrollment(face_id_name_list *face_list, dl_matrix3d_t *new_id)

                                                                              ^

D:\FaceDoorEntryESP32Cam\FaceDoorEntryESP32Cam.ino: In function 'esp_err_t send_face_list(websockets::WebsocketsClient&)':

FaceDoorEntryESP32Cam:213:3: error: 'face_id_node' was not declared in this scope

   face_id_node *head = st_face_list.head;

   ^

FaceDoorEntryESP32Cam:213:17: error: 'head' was not declared in this scope

   face_id_node *head = st_face_list.head;

                 ^

FaceDoorEntryESP32Cam:213:24: error: 'st_face_list' was not declared in this scope

   face_id_node *head = st_face_list.head;

                        ^

D:\FaceDoorEntryESP32Cam\FaceDoorEntryESP32Cam.ino: In function 'esp_err_t delete_all_faces(websockets::WebsocketsClient&)':

FaceDoorEntryESP32Cam:225:39: error: 'st_face_list' was not declared in this scope

   delete_face_all_in_flash_with_name(&st_face_list);

                                       ^

FaceDoorEntryESP32Cam:225:51: error: 'delete_face_all_in_flash_with_name' was not declared in this scope

   delete_face_all_in_flash_with_name(&st_face_list);

                                                   ^

D:\FaceDoorEntryESP32Cam\FaceDoorEntryESP32Cam.ino: In function 'void handle_message(websockets::WebsocketsClient&, websockets::WebsocketsMessage)':

FaceDoorEntryESP32Cam:241:39: error: 'ENROLL_NAME_LEN' was not declared in this scope

     char person[FACE_ID_SAVE_NUMBER * ENROLL_NAME_LEN] = {0,};

                                       ^

FaceDoorEntryESP32Cam:242:41: error: 'person' was not declared in this scope

     msg.data().substring(8).toCharArray(person, sizeof(person));

                                         ^

FaceDoorEntryESP32Cam:243:20: error: 'struct httpd_resp_value' has no member named 'enroll_name'

     memcpy(st_name.enroll_name, person, strlen(person) + 1);

                    ^

FaceDoorEntryESP32Cam:251:17: error: 'ENROLL_NAME_LEN' was not declared in this scope

     char person[ENROLL_NAME_LEN * FACE_ID_SAVE_NUMBER];

                 ^

FaceDoorEntryESP32Cam:252:41: error: 'person' was not declared in this scope

     msg.data().substring(7).toCharArray(person, sizeof(person));

                                         ^

FaceDoorEntryESP32Cam:253:40: error: 'st_face_list' was not declared in this scope

     delete_face_id_in_flash_with_name(&st_face_list, person);

                                        ^

FaceDoorEntryESP32Cam:253:60: error: 'delete_face_id_in_flash_with_name' was not declared in this scope

     delete_face_id_in_flash_with_name(&st_face_list, person);

                                                            ^

D:\FaceDoorEntryESP32Cam\FaceDoorEntryESP32Cam.ino: In function 'void loop()':

FaceDoorEntryESP32Cam:303:53: error: 'get_face_id' was not declared in this scope

           out_res.face_id = get_face_id(aligned_face);

                                                     ^

FaceDoorEntryESP32Cam:311:51: error: 'st_face_list' was not declared in this scope

             int left_sample_face = do_enrollment(&st_face_list, out_res.face_id);

                                                   ^

FaceDoorEntryESP32Cam:311:80: error: 'do_enrollment' cannot be used as a function

             int left_sample_face = do_enrollment(&st_face_list, out_res.face_id);

                                                                                ^

FaceDoorEntryESP32Cam:313:116: error: 'struct httpd_resp_value' has no member named 'enroll_name'

             sprintf(enrolling_message, "SAMPLE NUMBER %d FOR %s", ENROLL_CONFIRM_TIMES - left_sample_face, st_name.enroll_name);

                                                                                                                    ^

FaceDoorEntryESP32Cam:327:49: error: 'st_face_list' was not declared in this scope

           if (g_state == START_RECOGNITION  && (st_face_list.count > 0))

                                                 ^

FaceDoorEntryESP32Cam:329:13: error: 'face_id_node' was not declared in this scope

             face_id_node *f = recognize_face_with_name(&st_face_list, out_res.face_id);

             ^

FaceDoorEntryESP32Cam:329:27: error: 'f' was not declared in this scope

             face_id_node *f = recognize_face_with_name(&st_face_list, out_res.face_id);

                           ^

FaceDoorEntryESP32Cam:329:86: error: 'recognize_face_with_name' was not declared in this scope

             face_id_node *f = recognize_face_with_name(&st_face_list, out_res.face_id);

                                                                                      ^

"WiFi.h" için birden fazla library bulundu
Kullanılıyor: C:\Users\ARDA Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.33.0_x86__mdqgnx93n4wtt\libraries\WiFi
exit status 1
'face_id_name_list' was not declared in this scope

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by robotzero1** [comment]
OK.. I think you need to update the ESP32 libraries. Try this tutorial to see if it works - https://robotzero.one/esp32-cam-arduino-ide/

**Comment by Arda-Coskun** [comment]
Ok,I will try it also thank you

**Comment by Arda-Coskun** [comment]
Thank you so much it work.

**Comment by Arda-Coskun** [comment]
Also can you help me I have another problem
problem:
Arduino: 1.8.12 (Windows Store 1.8.33.0) (Windows 10), card:"ESP32 Wrover Module, Face Recognition (2621440 bytes), QIO, 80MHz, 921600, Verbose"

Your work used 2178579 bytes (83 %) of the program's storage space. Maximum 2621440 bytes.
Global variables use up to 45224 bytes (13%) of memory. Local variables remain at 282456 bytes. Up to 327680 bytes are available.
esptool.py v2.Six
Serial port COM5
Connecting........_____....._____....._____....._____....._____....._____....._____

A fatal error occurred: Failed to connect to ESP32: Invalid head of packet (0x65)
A fatal error occurred: Failed to connect to ESP32: Invalid head of packet (0x65)

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by robotzero1** [comment]
Probably it's a dodgy connection between the USB to Serial and the ESP32CAM. Try wriggling the wires a bit.

**Comment by Arda-Coskun** [comment]
That problem solved but I can't find the url

**Comment by Arda-Coskun** [comment]
I solve it

**Comment by Arda-Coskun** [comment]
I can't find URL pls help me, I load the code.
I just find:
rst:0x3 (SW_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1216
ho 0 tail 12 room 4
load:0x40078000,len:9720
ho 0 tail 12 room 4
load:0x40080400,len:6352
entry 0x400806b8

**Comment by robotzero1** [comment]
Looks like it's stopping before it gets to start the Wi-Fi. Try adding some Serial.println() statements into the void setup() function to see how far it's getting.

**Comment by Arda-Coskun** [comment]
But in code we have one void setup() and it also added

**Comment by robotzero1** [comment]
Like this in the existing void setup(). Put in lots before each part and you can see where the code is stopping.


```
void setup()
{
  Serial.begin(115200);
  Serial.println("Serial started");
  etc...
```
